-- Smart Academic Performance Prediction System
-- PostgreSQL schema import script
-- Run this while connected to the target database (for example: academic_perf_db)

BEGIN;

CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    age INTEGER NOT NULL,
    course VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS performance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    attendance DOUBLE PRECISION NOT NULL,
    quiz_score DOUBLE PRECISION NOT NULL,
    assignment_score DOUBLE PRECISION NOT NULL,
    study_hours DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_performance_student
        FOREIGN KEY (student_id)
        REFERENCES students (id)
);

CREATE TABLE IF NOT EXISTS predictions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL,
    predicted_grade VARCHAR(10) NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    failure_probability DOUBLE PRECISION NOT NULL,
    recommendations TEXT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_predictions_student
        FOREIGN KEY (student_id)
        REFERENCES students (id)
);

CREATE INDEX IF NOT EXISTS idx_performance_student_id ON performance (student_id);
CREATE INDEX IF NOT EXISTS idx_predictions_student_id ON predictions (student_id);
CREATE INDEX IF NOT EXISTS idx_predictions_risk_level ON predictions (risk_level);

COMMIT;
